---
abstract: 'Execute loops using parallel forked subprocesses'
author:
  - 'Peter Valdemar Mørch <peter@morch.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.84
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-Loops
no_index:
  directory:
    - inc
    - t
requires:
  Parallel::ForkManager: 0.7.9
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/pmorch/perl-Parallel-Loops
version: 0.07
